<<<<<<< HEAD
# Generated by Django 3.2.16 on 2022-11-17 00:54
=======
# Generated by Django 3.2.16 on 2022-11-16 11:45
>>>>>>> origin

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default='', max_length=250, verbose_name='question')),
                ('resp', models.CharField(max_length=15, verbose_name='telefono')),
                ('state', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
            ],
            options={
                'verbose_name': 'faq',
                'verbose_name_plural': 'faqs',
            },
        ),
    ]
