# Generated by Django 3.2.16 on 2022-11-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faq', '0002_faq_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='resp',
            field=models.CharField(max_length=400, verbose_name='telefono'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='type',
            field=models.CharField(max_length=20, verbose_name='tipo'),
        ),
    ]
