# Generated by Django 3.2.16 on 2022-11-30 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relaxation_space', '0002_remove_image_space_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image_space',
            old_name='img_space',
            new_name='space_img',
        ),
    ]
