# Generated by Django 3.2.16 on 2022-11-30 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaxation_space', '0003_rename_img_space_image_space_space_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image_space',
            name='space_img',
            field=models.ImageField(blank=True, null=True, upload_to='relaxation_space', verbose_name='space image'),
        ),
    ]
