# Generated by Django 3.2.16 on 2022-12-03 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaxation_space', '0004_alter_image_space_space_img'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='music_space',
            new_name='sound_space',
        ),
        migrations.AlterField(
            model_name='gif_space',
            name='gif_space',
            field=models.ImageField(blank=True, null=True, upload_to='space'),
        ),
    ]
