# Generated by Django 3.2.16 on 2022-12-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relaxation_space', '0005_auto_20221202_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sound_space',
            name='music_space',
            field=models.FileField(blank=True, null=True, upload_to='sound_space'),
        ),
    ]
