# Generated by Django 3.2.16 on 2022-10-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20221010_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_client',
            field=models.BooleanField(default=True, verbose_name='Cliente'),
        ),
    ]
