# Generated by Django 3.2.16 on 2022-11-03 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userstandard_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstandard',
            name='matricula',
        ),
    ]
