# Generated by Django 3.2.16 on 2022-11-03 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_userstandard_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstandard',
            name='matricula',
            field=models.CharField(default='', max_length=12, verbose_name='matricula'),
        ),
    ]
