# Generated by Django 3.2.16 on 2022-11-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userstandard_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstandard',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='birth date'),
        ),
        migrations.AddField(
            model_name='userstandard',
            name='ubication',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ubication'),
        ),
    ]
