# Generated by Django 3.2.16 on 2022-11-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20221107_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_profesional',
            field=models.ImageField(blank=True, null=True, upload_to='user'),
        ),
    ]
