# Generated by Django 3.2.16 on 2022-11-09 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_userstandard_deleted'),
        ('users', '0009_user_imagen_profesional'),
    ]

    operations = [
    ]
