# Generated by Django 3.2.16 on 2022-10-11 00:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='alternative_text',
        ),
        migrations.RemoveField(
            model_name='test',
            name='testregister',
        ),
        migrations.AddField(
            model_name='testregister',
            name='test',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaire.test'),
            preserve_default=False,
        ),
    ]
