# Generated by Django 3.2.16 on 2022-10-11 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_auto_20221010_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='resp_alternative',
            field=models.ManyToManyField(to='questionnaire.TestRegister'),
        ),
    ]
