# Generated by Django 3.2.16 on 2022-10-15 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_alternative_resp_alternative'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alternative',
            old_name='alernative',
            new_name='alternative',
        ),
    ]
