# Generated by Django 3.2.16 on 2022-10-15 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_rename_alernative_alternative_alternative'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(default='01-01-2022', max_length=100, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='introduction_text',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='introduction text'),
        ),
        migrations.AddField(
            model_name='test',
            name='pretest_text',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='pretest text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.CharField(max_length=200, verbose_name='text'),
        ),
    ]
