# Generated by Django 3.2.16 on 2022-10-15 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20221015_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alternative',
            name='resp_alternative',
        ),
    ]
