# Generated by Django 3.2.16 on 2022-10-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_remove_alternative_resp_alternative'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuestas_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.IntegerField(verbose_name={0, 1, 2, 3})),
                ('question_text', models.CharField(max_length=200, verbose_name='text')),
                ('question_type', models.CharField(max_length=100, verbose_name='type')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
                ('testregister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.testregister')),
            ],
            options={
                'verbose_name': 'alternative',
                'verbose_name_plural': 'alternative',
            },
        ),
    ]
