# Generated by Django 3.2.16 on 2022-10-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_respuestas_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuestas_user',
            name='question_id',
            field=models.IntegerField(default=-2020),
            preserve_default=False,
        ),
    ]
