# Generated by Django 3.2.16 on 2022-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_respuestas_user_question_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='testregister',
            name='status',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
