# Generated by Django 3.2.16 on 2022-10-21 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0010_testregister_result_estres'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='state_config',
            field=models.BooleanField(default=False, verbose_name='config'),
        ),
    ]
