# Generated by Django 3.2.16 on 2022-10-27 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_test_state_config'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recomendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_msg', models.CharField(blank=True, max_length=600, null=True, verbose_name='pretest text')),
                ('level', models.CharField(blank=True, max_length=600, null=True, verbose_name='pretest text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
            ],
            options={
                'verbose_name': 'recomendacion',
                'verbose_name_plural': 'recomendacion',
            },
        ),
        migrations.CreateModel(
            name='Relaxation_techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_msg', models.CharField(blank=True, max_length=600, null=True, verbose_name='pretest text')),
                ('level', models.CharField(blank=True, max_length=600, null=True, verbose_name='pretest text')),
                ('url', models.CharField(blank=True, max_length=600, null=True, verbose_name='pretest text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
                ('recomendation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.recomendation')),
            ],
            options={
                'verbose_name': 'tecnica de relajación',
                'verbose_name_plural': 'tecnicas de relajación',
            },
        ),
    ]
