# Generated by Django 3.2.16 on 2022-10-31 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_recomendation_relaxation_techniques'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaxation_techniques',
            name='url',
        ),
        migrations.AddField(
            model_name='relaxation_techniques',
            name='state_professional',
            field=models.BooleanField(default=False, verbose_name='state professional'),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='level',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='recomendation',
            name='text_msg',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='recomendation text'),
        ),
        migrations.AlterField(
            model_name='relaxation_techniques',
            name='level',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='level'),
        ),
        migrations.AlterField(
            model_name='relaxation_techniques',
            name='text_msg',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='text'),
        ),
        migrations.CreateModel(
            name='Link_techniques',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_msg', models.CharField(blank=True, max_length=600, null=True, verbose_name='text')),
                ('url', models.CharField(blank=True, max_length=600, null=True, verbose_name='level')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
                ('relaxation_techniques', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.relaxation_techniques')),
            ],
            options={
                'verbose_name': 'url de tecnica',
                'verbose_name_plural': 'urls de tecnicas',
            },
        ),
    ]
