# Generated by Django 3.2.16 on 2022-10-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_recomendation_relaxation_techniques'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaxation_techniques',
            name='state_peofessional',
            field=models.BooleanField(default=False, verbose_name='state professional'),
        ),
    ]
