# Generated by Django 3.2.16 on 2022-10-31 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20221030_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relaxation_techniques',
            old_name='state_professional',
            new_name='state_professional',
        ),
    ]
