# Generated by Django 3.2.16 on 2022-11-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_rename_state_peofessional_relaxation_techniques_state_professional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link_techniques',
            name='text_msg',
        ),
        migrations.AddField(
            model_name='link_techniques',
            name='autor',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='autor'),
        ),
        migrations.AddField(
            model_name='link_techniques',
            name='canal',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='canal'),
        ),
        migrations.AddField(
            model_name='link_techniques',
            name='origen',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='level'),
        ),
        migrations.AddField(
            model_name='link_techniques',
            name='text_title',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='text title'),
        ),
        migrations.AlterField(
            model_name='link_techniques',
            name='url',
            field=models.CharField(blank=True, max_length=600, null=True, verbose_name='url'),
        ),
    ]
