# Generated by Django 3.2.16 on 2022-11-04 13:16

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20221031_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link_techniques',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=-AOPAqxAFJk'),
            preserve_default=False,
        ),
    ]
