# Generated by Django 3.2.16 on 2022-11-04 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_relaxation_techniques_state_peofessional'),
        ('questionnaire', '0016_alter_link_techniques_url'),
    ]

    operations = [
    ]
