<<<<<<< HEAD
# Generated by Django 3.2.16 on 2022-11-07 19:12
=======
# Generated by Django 3.2.16 on 2022-11-05 01:15
>>>>>>> origin

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_merge_20221104_1154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relaxation_techniques',
<<<<<<< HEAD
            name='state_peofessional',
=======
            name='state_professional',
>>>>>>> origin
        ),
    ]
