# Generated by Django 3.2.16 on 2022-11-05 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_remove_relaxation_techniques_state_peofessional'),
    ]

    operations = [
        migrations.AddField(
            model_name='relaxation_techniques',
            name='state_professional',
            field=models.BooleanField(default=False, verbose_name='state professional'),
        ),
    ]
