# Generated by Django 3.2.16 on 2022-12-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diarioemocional', '0002_remove_entrada_img_emocion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrada',
            name='emocion',
            field=models.CharField(max_length=30),
        ),
    ]
