# Generated by Django 3.2.16 on 2022-12-07 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diarioemocional', '0003_alter_entrada_emocion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Emocion',
        ),
    ]
