# Generated by Django 3.2.16 on 2022-10-10 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='infoOrg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('long_name', models.CharField(max_length=100, verbose_name='long name')),
                ('short_name', models.CharField(max_length=20, verbose_name='short name')),
                ('description', models.CharField(max_length=300, verbose_name='description')),
                ('color_1', models.CharField(max_length=10, verbose_name='color 1')),
                ('color_2', models.CharField(max_length=10, verbose_name='color 2')),
                ('color_3', models.CharField(max_length=10, verbose_name='color 3')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
            ],
            options={
                'verbose_name': 'info org',
                'verbose_name_plural': 'info org',
            },
        ),
    ]
