# Generated by Django 3.2.16 on 2022-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='thermometer_config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_1', models.CharField(default='#3BB44A', max_length=10, verbose_name='color rgba1')),
                ('color_2', models.CharField(default='#FEDA33', max_length=10, verbose_name='color rgba2')),
                ('color_3', models.CharField(default='#EC1B1E', max_length=10, verbose_name='color rgba3')),
                ('color_4', models.CharField(default='#FC7535', max_length=10, verbose_name='color rgba4')),
                ('color_5', models.CharField(default='#55E659', max_length=10, verbose_name='color rgba5')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha creacion')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha actualizacion')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha eliminacion')),
            ],
            options={
                'verbose_name': 'comfig colors',
                'verbose_name_plural': 'config colors',
            },
        ),
    ]
