# Generated by Django 3.2.16 on 2022-11-22 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdass', '0002_thermometer_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thermometer_config',
            name='color_1',
            field=models.CharField(default='#55E659', max_length=10, verbose_name='color rgba1'),
        ),
        migrations.AlterField(
            model_name='thermometer_config',
            name='color_2',
            field=models.CharField(default='#3BB44A', max_length=10, verbose_name='color rgba2'),
        ),
        migrations.AlterField(
            model_name='thermometer_config',
            name='color_3',
            field=models.CharField(default='#FEDA33', max_length=10, verbose_name='color rgba3'),
        ),
        migrations.AlterField(
            model_name='thermometer_config',
            name='color_5',
            field=models.CharField(default='#EC1B1E', max_length=10, verbose_name='color rgba5'),
        ),
    ]
