# Generated by Django 3.2.16 on 2022-10-18 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen_profesional', models.ImageField(null=True, upload_to='profesional')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('apellido', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido')),
                ('curp', models.CharField(max_length=20, verbose_name='CURP')),
                ('correo', models.EmailField(blank=True, max_length=300, null=True)),
                ('numero_1', models.IntegerField(blank=True, max_length=15, null=True)),
                ('numero_2', models.IntegerField(blank=True, max_length=15, null=True)),
                ('redes', models.CharField(blank=True, max_length=300, null=True)),
                ('ubicacion', models.CharField(blank=True, max_length=500, null=True)),
                ('especialidades', models.CharField(blank=True, max_length=500, null=True)),
                ('servicios', models.CharField(blank=True, max_length=300, null=True)),
                ('valor', models.IntegerField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
