# Generated by Django 3.2.16 on 2022-10-21 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
    ]
