# Generated by Django 3.2.16 on 2022-10-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='imagen_profesional',
            field=models.ImageField(blank=True, null=True, upload_to='profesional'),
        ),
    ]
