# Generated by Django 3.2.16 on 2022-10-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0002_alter_profesional_imagen_profesional'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesional',
            name='curp',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='servicios',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='valor',
        ),
        migrations.AddField(
            model_name='profesional',
            name='horario_laboral',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='profesional',
            name='servicios_valor',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
