# Generated by Django 3.2.16 on 2022-10-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profesional', '0003_auto_20221027_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesional',
            name='numero_1',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='profesional',
            name='numero_2',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
