# Generated by Django 3.2.16 on 2022-12-10 20:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manualcrisis', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manual',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='manual',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='manual',
            name='dateTimeUploaded',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
