# Generated by Django 3.2.16 on 2022-12-11 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manualcrisis', '0002_auto_20221210_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='manual',
            old_name='file',
            new_name='manual',
        ),
    ]
