# Generated by Django 3.2.16 on 2022-12-11 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manualcrisis', '0005_alter_termscondition_uploadpdf'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='termsCondition',
            new_name='Manual',
        ),
    ]
