# Generated by Django 3.2.16 on 2022-11-25 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diario_emocional', '0002_alter_entrada_emocion'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='img_emocion',
            field=models.ImageField(blank=True, null=True, upload_to='emocion'),
        ),
    ]
