# Generated by Django 3.2.16 on 2022-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='termscondition',
            name='uploadFile',
            field=models.FileField(blank=True, null=True, upload_to='Uploaded Files/'),
        ),
    ]
