# Generated by Django 3.2.16 on 2022-11-20 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_web', '0002_alter_termscondition_uploadfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='termscondition',
            old_name='uploadFile',
            new_name='uploadPDF',
        ),
    ]
